### ISSUE TITLE
timeline::metrics failing nestest tests

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1281]
```
cargo install cargo-nextest
cargo nextest run
```
produces these results:
```
--- STDOUT:              hayabusa timeline::metrics::tests::test_evt_logon_stats ---

running 1 test
test timeline::metrics::tests::test_evt_logon_stats ... FAILED

failures:

failures:
    timeline::metrics::tests::test_evt_logon_stats

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 330 filtered out; finished in 0.04s


--- STDERR:              hayabusa timeline::metrics::tests::test_evt_logon_stats ---
thread 'timeline::metrics::tests::test_evt_logon_stats' panicked at src/detections/utils.rs:319:43:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   Canceling due to test failure: 15 tests still running
        PASS [   0.078s] hayabusa timeline::computer_metrics::tests::test_computer_metrics_dsp_msg
        PASS [   0.079s] hayabusa timeline::timelines::tests::test_evt_logon_stats
        PASS [   0.082s] hayabusa timeline::timelines::tests::test_tm_logon_stats_dsp_msg
        PASS [   0.081s] hayabusa timeline::timelines::tests::test_tm_stats_dsp_msg
        PASS [   0.087s] hayabusa yaml::tests::test_all_exclude_rules_file
        PASS [   0.087s] hayabusa yaml::tests::test_all_noisy_rules_file
        PASS [   0.083s] hayabusa yaml::tests::test_critical_exact_level_read_yaml
        PASS [   0.082s] hayabusa yaml::tests::test_critical_level_read_yaml
        PASS [   0.033s] hayabusa yaml::tests::test_failed_read_yaml
        PASS [   0.078s] hayabusa yaml::tests::test_exclude_category_option_1opt
        PASS [   0.084s] hayabusa yaml::tests::test_default_level_read_yaml
        PASS [   0.148s] hayabusa options::profile::tests::test_load_profile
        PASS [   0.079s] hayabusa yaml::tests::test_exclude_category_option_multi_opt
        PASS [   0.068s] hayabusa yaml::tests::test_exclude_category_option_notfound
        PASS [   0.064s] hayabusa yaml::tests::test_exclude_deprecated_rules_file
        PASS [   0.060s] hayabusa yaml::tests::test_exclude_unsupported_rules_file
        PASS [   0.059s] hayabusa yaml::tests::test_high_exact_level_read_yaml
------------
     Summary [   2.263s] 316/347 tests run: 315 passed, 1 failed, 0 skipped
        FAIL [   0.073s] hayabusa timeline::metrics::tests::test_evt_logon_stats
error: test run failed
```

Not a high priority issue but would be nice to fix this test.

**Comment by Shirofune-Security** [comment]
Looked into this — opened #1798 with a fix.

**Root cause:** `test_evt_logon_stats` calls `create_rec_info`, which reads the process-global `STORED_EKEY_ALIAS` (`RwLock<Option<EventKeyAliasConfig>>`, initially `None`):

```rust
let binding = STORED_EKEY_ALIAS.read().unwrap();
let eventkey_alias = binding.as_ref().unwrap();   // panics when None
```

Every other `create_rec_info` test sets that global first (the sibling `timeline::timelines::tests::test_evt_logon_stats`, `rule::count`, `rule::mod`, …). This one doesn't. Under plain `cargo test` all tests share one process, so another test populates the global first and it passes by ordering luck. Under `nextest`'s **process-per-test isolation** nothing sets it → the `unwrap()` hits `None`. That's the `src/detections/utils.rs` `Option::unwrap() on None` panic in the report.

**Fix:** initialize `STORED_EKEY_ALIAS` from the test's own dummy config before `create_rec_info`, matching the sibling tests. Since the alias is loaded from the same `rules/config/eventkey_alias.txt` everywhere, the written value is identical to what other tests write — no new race in the multi-threaded runner.

**Verified** (nextest's prebuilt binary wouldn't execute in my environment, so I emulated its per-test isolation with `<test-binary> --exact <name>`):
- isolated `test_evt_logon_stats`: ❌ panics at `utils.rs:336` before / ✅ passes after
- all `timeline::` tests run one-per-process: ✅ pass
- regression: full multi-threaded `cargo test --lib` → 423 pass, 25/25 runs green

**Comment by Shirofune-Security** [comment]
Follow-up: after #1798, `cargo nextest run` still fails a second class of tests — the output-overwrite bin tests (`test_same_file_output_logon_summary_csv_exit`, `..._computer_metrics_exit`, `..._metric_csv_exit`) with `assertion left == right failed, left: 214, right: 0`.

Cause is the same nextest characteristic: these tests come in pairs sharing a fixed output filename, previously serialized by an **in-process** `Mutex`. nextest runs each test in its **own process**, so the mutex serializes nothing and the clobber variant writes the file the `*_exit` variant asserts is empty.

Fixed in #1799 by giving each test a unique filename (and dropping the now-pointless lock). Verified by emulating nextest's per-test-process model: before = 61 failures / 400 concurrent runs, after = 0 / 600.
